import { FormEvent, useCallback, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { SearchResults } from "../components/SearchResults";
import { api } from "../services/api";

type ResultsData = {
  id: number;
  price: number;
  title: string;
  priceFormatted: string;
};

type Results = {
  totalPrice: number;
  data: ResultsData[];
};

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const [results, setResults] = useState<Results>({
    totalPrice: 0,
    data: [],
  });

  async function handleSearch(event: FormEvent) {
    event.preventDefault();

    const formatter = new Intl.NumberFormat("pt-BR", {
      style: "currency",
      currency: "BRL",
    }).format;

    if (!search.trim()) return;

    try {
      const response = await api.get<ResultsData[]>("products", {
        params: {
          q: search.trim(),
        },
      });

      const totalPrice = response.data.reduce((total, product) => {
        return total + product.price;
      }, 0);

      const products = response.data.map((product) => {
        return {
          id: product.id,
          title: product.title,
          price: product.price,
          priceFormatted: formatter(product.price),
        };
      });

      setResults({
        totalPrice,
        data: products,
      });
    } catch {}
  }

  const addToWishlist = useCallback(async (id: number) => {
    console.log(id);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Search</h1>

        <form onSubmit={handleSearch}>
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <button>Buscar</button>
        </form>

        <SearchResults
          results={results.data}
          totalPrice={results.totalPrice}
          onAddToWishlist={addToWishlist}
        />
      </main>
    </div>
  );
};

export default Home;
